import { useState } from 'react'
import { parseSave, mergeSaves, summary, download, reviewQuestions, type Save, type Session } from '../core/learning'
export default function ProgressPage({data,language,change,resume,review,home}:{data:Save;language:'zh'|'en';change:(s:Save)=>void;resume:(s:Session)=>void;review:(s:Session)=>void;home:()=>void}){
 const [report,setReport]=useState<Save|null>(null),[notice,setNotice]=useState('')
 const t=(zh:string,en:string)=>language==='zh'?zh:en
 const source=report??data, stats=summary(source.sessions)
 async function load(file:File|undefined,teacher:boolean){if(!file)return;if(file.size>5_000_000){setNotice(t('存檔超過 5 MB','Save exceeds 5 MB'));return}try{const loaded=parseSave(await file.text());if(teacher){setReport(loaded);setNotice(`${file.name} · ${t('已開啟老師報告，未修改本機進度。','Teacher report opened. Local progress unchanged.')}`)}else{change(mergeSaves(data,loaded));setNotice(t('存檔已合併；相同回合不重複計算。','Save merged; duplicate sessions are not counted twice.'))}}catch(e){setNotice(e instanceof Error?e.message:String(e))}}
 return <section className="utility-page"><button className="game-link" onClick={home}>← {t('首頁','Home')}</button><h1>{report?t('老師存檔報告','Teacher save report'):t('學習進度與存檔','Learning progress & save')}</h1><p>{t('存檔包含逐題歷史；目前為未加密 JSON，不是成績防偽證明。','The save contains question history. It is unencrypted JSON, not a verified assessment record.')}</p><div className="utility-card"><div className="result-actions"><button className="primary-button" onClick={()=>download('word-bloom-save.json',JSON.stringify(source,null,2))}>{t('匯出學生 save','Export student save')}</button><label className="secondary-button file-button">{t('匯入學生 save／續玩','Import student save / resume')}<input type="file" accept=".json,application/json" onChange={e=>{void load(e.target.files?.[0],false);e.target.value=''}}/></label><label className="secondary-button file-button">{t('老師解讀 save','Teacher: read save')}<input type="file" accept=".json,application/json" onChange={e=>{void load(e.target.files?.[0],true);e.target.value=''}}/></label>{report&&<button className="secondary-button" onClick={()=>setReport(null)}>{t('返回本機進度','Local progress')}</button>}</div><p role="status">{notice}</p></div>
 <div className="progress-metrics">{[[t('回合','Rounds'),stats.rounds],[t('遊玩分鐘','Play minutes'),(stats.timeMs/60000).toFixed(1)],[t('出題次數','Questions shown'),stats.shown],[t('曾作答題数','Questions attempted'),stats.answered],[t('提交次數','Submissions'),stats.submissions],[t('不同答案詞','Distinct answer words'),stats.words],[t('氣球答對','Correct balloons'),stats.correct],[t('未匹配輸入','Unmatched inputs'),stats.unmatched],[t('回訪提交','Review attempts'),stats.reviews]].map(([label,value])=><div className="utility-card" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
 <p className="game-note">{t('重試只增加提交次數，不增加該回合題數。多氣球未匹配輸入是候選，單題未匹配才可確認目標；超時不等於答錯。回訪獨立計算。','Retries increase submissions, not question counts. Unmatched multi-balloon inputs are candidates; single-balloon targets can be confirmed. Timeout is not a wrong answer. Reviews are counted separately.')}</p>
 {!source.sessions.length&&<div className="utility-card">{t('暫時未有回合。先玩一次，再返來。','No sessions yet. Play a round first.')}</div>}
 {[...source.sessions].reverse().map(session=><SessionCard key={session.id} session={session} language={language} readOnly={!!report} resume={resume} review={review}/>)}
 <h2>{t('可比進步線索','Comparable progress clues')}</h2><p>{t('只比較同一提示、答案、題型及遊戲設定的紀錄；單題回訪與氣球結果分開。中途改讀音的氣球回合不納入比較；資料不足就不下結論。','Compare only matching prompts, answers, types and settings. Single-question reviews are separate from balloon results. Rounds with changed speech settings are excluded from balloon comparisons. Insufficient data does not establish progress.')}</p><div className="utility-card"><ProgressClues sessions={source.sessions} language={language}/></div>
 </section>
}
function SessionCard({session:s,language,readOnly,resume,review}:{session:Session;language:'zh'|'en';readOnly:boolean;resume:(s:Session)=>void;review:(s:Session)=>void}){
 const t=(zh:string,en:string)=>language==='zh'?zh:en;const candidates=reviewQuestions(s)
 return <article className="utility-card session-card"><h2>{s.level.id<=4?`Lv${s.level.id}`:t('自訂題庫','Custom bank')} · {s.level.title[language==='zh'?0:1]}</h2><p>{new Date(s.startedAt).toLocaleString()} · {t(s.round.finished?'已結束':'未完成',s.round.finished?'Finished':'Unfinished')} · {(s.round.elapsedMs/1000).toFixed(1)}s · {s.settings.balloonCount} {t('氣球','balloons')} / {s.settings.seconds}s</p>{!readOnly&&<div className="result-actions">{!s.round.finished&&<button className="primary-button" onClick={()=>resume(s)}>{t('續玩此回合','Resume this round')}</button>}{candidates.length>0&&<button className="secondary-button" onClick={()=>review(s)}>{t('單題回訪','Single-question review')} ({candidates.length})</button>}</div>}
 <div className="table-scroll"><table><thead><tr>{[t('提示 → 答案','Prompt → answers'),t('氣球結果','Balloon result'),t('單題回訪','Single-question review')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{s.level.questions.map(q=>{const outcome=s.round.outcomes.find(o=>o.questionId===q.id);const shown=s.round.shown.some(x=>x.questionId===q.id);const attempts=s.reviews.filter(a=>a.questionId===q.id);const wrongConfirmed=s.round.attempts.filter(a=>!a.questionId&&a.screen.length===1&&a.screen[0].questionId===q.id).length;return <tr key={q.id}><td>{q.prompt} → {q.answers.join(' / ')}</td><td>{outcome?.at&&<span>{new Date(outcome.at).toLocaleTimeString()} · </span>}{outcome?.result==='correct'?t('答對','Correct'):outcome?.result==='timeout'?t('超時未答','Timed out'):shown?t('已出題未完成','Shown, unfinished'):t('未出題','Not shown')}{wrongConfirmed>0&&` · ${t('確認錯答','Confirmed wrong')} ${wrongConfirmed}`}{candidates.some(x=>x.id===q.id)&&s.round.attempts.some(a=>!a.questionId&&a.screen.length>1&&a.screen.some(x=>x.questionId===q.id))&&` · ${t('錯答候選','Candidate')}`}</td><td>{attempts.length?attempts.map((a,i)=><span key={a.id}>{i+1}. {a.correct?'✓':'✗'} {a.input}{a.assisted?` (${t('已看答案','assisted')})`:''} · {(a.elapsedMs/1000).toFixed(1)}s<br/></span>):'—'}</td></tr>})}</tbody></table></div>
 <details><summary>{t('逐次提交與當時同屏題','Submissions and screen snapshots')}</summary>{s.round.attempts.map((a,i)=><p key={i}>{i+1}. {a.input} {a.at?`· ${new Date(a.at).toLocaleString()}`:''} · {(a.elapsedMs/1000).toFixed(1)}s · {a.questionId?'✓':t('未匹配','Unmatched')} · {a.screen.map(x=>`${x.prompt} (${Math.round(x.growth*100)}%)`).join(' / ')}</p>)}</details></article>
}
function ProgressClues({sessions,language}:{sessions:Session[];language:'zh'|'en'}){
 const t=(zh:string,en:string)=>language==='zh'?zh:en
 const groups=new Map<string,{prompt:string;items:{status:string;at:string}[];reviews:{correct:boolean;at:string}[]}>()
 for(const s of [...sessions].sort((a,b)=>a.startedAt.localeCompare(b.startedAt)))for(const q of s.level.questions){const key=JSON.stringify([s.level.id,q.prompt,q.answers,s.settings]);const group=groups.get(key)??{prompt:q.prompt,items:[],reviews:[]};const outcome=s.round.outcomes.find(o=>o.questionId===q.id);if(outcome&&!s.round.adjusted)group.items.push({status:outcome.result,at:s.startedAt});for(const a of s.reviews.filter(a=>a.questionId===q.id&&!a.assisted))group.reviews.push({correct:a.correct,at:a.at});groups.set(key,group)}
 const comparable=[...groups.values()].filter(g=>g.items.length>=2||g.reviews.length>=2)
 return comparable.length?<ul>{comparable.map((g,i)=><li key={i}>{g.prompt}: {g.items.length>=2&&`${t('氣球','Balloons')} ${g.items.map(x=>x.status==='correct'?'✓':t('超時','timeout')).join(' → ')}`}{g.reviews.length>=2&&` · ${t('回訪','Reviews')} ${g.reviews.map(x=>x.correct?'✓':'✗').join(' → ')}`}</li>)}</ul>:<p>{t('未有相同條件的兩次紀錄，暫時不足以比較。','Not enough matching records to compare yet.')}</p>
}
