import { useEffect, useRef, useState } from 'react'
import { reviewQuestions, type Session, type Review } from '../core/learning'
export default function ReviewPage({session,language,record,home}:{session:Session;language:'zh'|'en';record:(sessionId:string,attempt:Review)=>void;home:()=>void}){
 const questions=reviewQuestions(session),[index,setIndex]=useState(0),[input,setInput]=useState(''),[feedback,setFeedback]=useState(''),[done,setDone]=useState(false);const started=useRef(performance.now()), activeMs=useRef(0), assisted=useRef(false)
 useEffect(()=>{const visibility=()=>{if(document.hidden){activeMs.current+=performance.now()-started.current}else started.current=performance.now()};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility)},[])
 const t=(zh:string,en:string)=>language==='zh'?zh:en;const q=questions[index]
 // Response time is for this visible single-question attempt, not the original ambiguous input.
 function submit(){if(!q||!input.trim())return;const now=performance.now();const elapsed=activeMs.current+(document.hidden?0:now-started.current);const correct=q.answers.some(a=>a.toLowerCase()===input.trim().normalize('NFC').toLowerCase());record(session.id,{id:crypto.randomUUID(),questionId:q.id,input:input.trim(),correct,assisted:assisted.current,at:new Date().toISOString(),elapsedMs:Math.max(0,elapsed)});activeMs.current=0;started.current=now;setFeedback(correct?t('答對！按下一題。','Correct! Move to the next question.'):t('未配對，可修改再試，或查看答案後再練。','No match. Edit and retry, or check the answer and practice again.'));}
 return <section className="utility-page"><button className="game-link" onClick={home}>← {t('進度','Progress')}</button><h1>{t('單題回訪','Single-question review')}</h1><p>{t('這次只有一題，提交可確認目標。原本多氣球錯答仍保持候選，不倒改歷史。','One question at a time confirms the target. Earlier ambiguous inputs remain candidates.')}</p>{done||!q?<div className="utility-card"><h2>{t('回訪紀錄已保存。','Review records saved.')}</h2><button className="primary-button" onClick={home}>{t('查看進度','View progress')}</button></div>:<div className="utility-card review-card"><span>Lv{session.level.id} · {index+1}/{questions.length}</span><h2>{q.prompt}</h2><form onSubmit={e=>{e.preventDefault();submit()}}><input aria-label={t('回訪答案','Review answer')} maxLength={1000} autoFocus value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setInput('');if(e.key==='Enter'&&e.nativeEvent.isComposing)e.preventDefault()}}/><button className="primary-button">{t('提交','Submit')}</button></form><p role="status">{feedback}</p><details key={q.id} onToggle={e=>{if(e.currentTarget.open){assisted.current=true;setFeedback(t('已看答案，本題之後作答不視為無提示。','Answer viewed; subsequent attempts are assisted.'))}}}><summary>{t('查看答案','Show answers')}</summary>{q.answers.join(' / ')}</details><button className="secondary-button" onClick={()=>{if(index+1===questions.length)setDone(true);else {setIndex(index+1);setInput('');setFeedback('');started.current=performance.now();activeMs.current=0;assisted.current=false}}}>{t('下一題／略過','Next / skip')} →</button></div>}</section>
}
