const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'word-bloom-tests-'));try{
const compiled=spawnSync('./node_modules/.bin/tsc',['src/core/learning.ts','src/core/csv.ts','--target','es2022','--module','commonjs','--outDir',dir,'--skipLibCheck'],{encoding:'utf8'});if(compiled.status!==0)throw new Error(compiled.stdout+compiled.stderr);
const {createRound,submit,tick}=require(path.join(dir,'core/balloon.js'));const {LEVELS}=require(path.join(dir,'data/levels.js'));const {DEFAULT_SETTINGS}=require(path.join(dir,'core/settings.js'));const {emptySave,newSession,parseSave,mergeSaves,summary,reviewQuestions}=require(path.join(dir,'core/learning.js'));const {csvExample,importCSV,parseCSV}=require(path.join(dir,'core/csv.js'));
for(const level of LEVELS){for(const count of [1,2,3]){const settings={...DEFAULT_SETTINGS,balloonCount:count,seconds:20};const session=newSession(level,settings),r=session.round;assert.equal(r.balloons.length,count);assert.ok(r.balloons.every(b=>b.limitMs>=18000&&b.limitMs<=22000));submit(r,'oops');assert.equal(r.lives,3);assert.equal(reviewQuestions(session).length,count);while(!r.finished){const q=r.balloons[0].question;submit(r,q.answers.at(-1));}assert.equal(r.outcomes.length,10);const save={...emptySave(),sessions:[session],activeId:session.id};assert.deepEqual(parseSave(JSON.stringify(save)),save);assert.equal(mergeSaves(save,save).sessions.length,1);assert.equal(summary([session]).submissions,11);assert.equal(summary([session]).shown,10);}}
const partial=newSession(LEVELS[1],DEFAULT_SETTINGS);tick(partial.round,1100);const saved={...emptySave(),sessions:[partial],activeId:partial.id};const loaded=parseSave(JSON.stringify(saved));assert.equal(loaded.sessions[0].round.elapsedMs,1100);assert.equal(loaded.sessions[0].round.finished,false);const prior=structuredClone(saved);submit(partial.round,partial.round.balloons[0].question.answers[0]);const merged=mergeSaves(saved,prior);assert.equal(merged.sessions[0].round.outcomes.length,1);partial.reviews.push({id:'r1',questionId:partial.level.questions[0].id,input:'wrong',correct:false,assisted:false,at:new Date().toISOString(),elapsedMs:1000});assert.equal(mergeSaves(saved,saved).sessions[0].reviews.length,1);
for(const change of [x=>x.version=999,x=>x.sessions[0].round.lives=99,x=>x.sessions[0].round.balloons[0].limitMs=-1,x=>x.sessions[0].round.order=[],x=>x.activeId='missing']){const bad=structuredClone(saved);change(bad);assert.throws(()=>parseSave(JSON.stringify(bad)));}assert.throws(()=>parseSave('{broken'));tick(partial.round,40000);assert.equal(partial.round.lives,0);parseSave(JSON.stringify(saved));
for(const level of LEVELS){const example=csvExample(level),bank=importCSV(example,level,'test',1001);assert.deepEqual(bank.questions.map(q=>[q.prompt,q.answers]),level.questions.map(q=>[q.prompt,q.answers]));fs.writeFileSync(path.join('csv-examples',`lv${level.id}-example.csv`),example);}
assert.deepEqual(parseCSV('a,b\n"hello, world","say ""yes"""'),[['a','b'],['hello, world','say "yes"']]);assert.throws(()=>parseCSV('"bad'));assert.throws(()=>importCSV('prompt,answer,answer2,answer3\nx,a,,\ny,A,,',LEVELS[0],'bad',999));assert.throws(()=>importCSV('prompt,answer\nx,a',LEVELS[0],'bad',999));assert.ok(LEVELS[3].questions.every(q=>q.prompt.split(/\s+/).length<=5));console.log('PASS: settings, all levels, counters, save resume/merge/validation, review candidates, CSV roundtrip/errors');
}finally{fs.rmSync(dir,{recursive:true,force:true})}
